# Nome da Actions
name: Snake Game

# Controlador do tempo que será feito a atualização dos arquivos
on:
  schedule:
    # Será atualizado a cada 5 horas
    - cron: "0 */5 * * *"

  # Permite execução manual
  workflow_dispatch:

# Permissões explícitas para permitir push
permissions:
  contents: write

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Geração dos arquivos da cobrinha
      - name: Gerar a animação da cobrinha
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Lucas-Laudenir  # Seu usuário
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Exibir status do Git
      - name: Verificar status do Git
        run: git status

      # Configurar Git para commit
      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Commit e push das alterações
      - name: Commit e push das alterações
        run: |
          git add .
          git commit -m "Atualização automática da cobrinha 🐍"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Atualização da página do GitHub Pages
      - name: Atualizar GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
